// Auto-generated type definitions for Photon
// This file is generated by scripts/generate-photon-types.ts
// DO NOT EDIT THIS FILE MANUALLY

// Global function declarations - use functions directly (e.g., grayscale(image))

declare function add_noise_rand(photon_image: PhotonImage): void;
declare function adjust_brightness(photon_image: PhotonImage, brightness: number): void;
declare function adjust_contrast(photon_image: PhotonImage, contrast: number): void;
declare function alter_blue_channel(img: PhotonImage, amt: number): void;
declare function alter_channel(img: PhotonImage, channel: number, amt: number): void;
declare function alter_channels(img: PhotonImage, r_amt: number, g_amt: number, b_amt: number): void;
declare function alter_green_channel(img: PhotonImage, amt: number): void;
declare function alter_red_channel(photon_image: PhotonImage, amt: number): void;
declare function alter_two_channels(img: PhotonImage, channel1: number, amt1: number, channel2: number, amt2: number): void;
declare function apply_gradient(image: PhotonImage): void;
declare function b_grayscale(photon_image: PhotonImage): void;
declare function base64_to_image(base64: string): PhotonImage;
declare function base64_to_vec(base64: string): Uint8Array;
declare function blend(photon_image: PhotonImage, photon_image2: PhotonImage, blend_mode: string): void;
declare function box_blur(photon_image: PhotonImage): void;
declare function cali(img: PhotonImage): void;
declare function color_horizontal_strips(photon_image: PhotonImage, num_strips: number, color: Rgb): void;
declare function color_vertical_strips(photon_image: PhotonImage, num_strips: number, color: Rgb): void;
declare function colorize(photon_image: PhotonImage): void;
declare function create_gradient(width: number, height: number): PhotonImage;
declare function crop(photon_image: PhotonImage, x1: number, y1: number, x2: number, y2: number): PhotonImage;
declare function crop_img_browser(source_canvas: HTMLCanvasElement, width: number, height: number, left: number, top: number): HTMLCanvasElement;
declare function darken_hsl(img: PhotonImage, level: number): void;
declare function darken_hsluv(img: PhotonImage, level: number): void;
declare function darken_hsv(img: PhotonImage, level: number): void;
declare function darken_lch(img: PhotonImage, level: number): void;
declare function dec_brightness(photon_image: PhotonImage, brightness: number): void;
declare function decompose_max(img: PhotonImage): void;
declare function decompose_min(img: PhotonImage): void;
declare function desaturate(img: PhotonImage): void;
declare function desaturate_hsl(img: PhotonImage, level: number): void;
declare function desaturate_hsluv(img: PhotonImage, level: number): void;
declare function desaturate_hsv(img: PhotonImage, level: number): void;
declare function desaturate_lch(img: PhotonImage, level: number): void;
declare function detect_135_deg_lines(photon_image: PhotonImage): void;
declare function detect_45_deg_lines(photon_image: PhotonImage): void;
declare function detect_horizontal_lines(photon_image: PhotonImage): void;
declare function detect_vertical_lines(photon_image: PhotonImage): void;
declare function dither(photon_image: PhotonImage, depth: number): void;
declare function dramatic(img: PhotonImage): void;
declare function draw_text(photon_img: PhotonImage, text: string, x: number, y: number, font_size: number): void;
declare function draw_text_with_border(photon_img: PhotonImage, text: string, x: number, y: number, font_size: number): void;
declare function duotone(photon_image: PhotonImage, color_a: Rgb, color_b: Rgb): void;
declare function duotone_horizon(img: PhotonImage): void;
declare function duotone_lilac(img: PhotonImage): void;
declare function duotone_ochre(img: PhotonImage): void;
declare function duotone_tint(img: PhotonImage, rgb_color: Rgb): void;
declare function duotone_violette(img: PhotonImage): void;
declare function edge_detection(photon_image: PhotonImage): void;
declare function edge_one(photon_image: PhotonImage): void;
declare function emboss(photon_image: PhotonImage): void;
declare function filter(img: PhotonImage, filter_name: string): void;
declare function firenze(img: PhotonImage): void;
declare function fliph(photon_image: PhotonImage): void;
declare function flipv(photon_image: PhotonImage): void;
declare function frosted_glass(photon_image: PhotonImage): void;
declare function g_grayscale(photon_image: PhotonImage): void;
declare function gamma_correction(photon_image: PhotonImage, red: number, green: number, blue: number): void;
declare function gaussian_blur(photon_image: PhotonImage, radius: number): void;
declare function get_image_data(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D): ImageData;
declare function golden(img: PhotonImage): void;
declare function grayscale(img: PhotonImage): void;
declare function grayscale_human_corrected(img: PhotonImage): void;
declare function grayscale_shades(photon_image: PhotonImage, num_shades: number): void;
declare function halftone(photon_image: PhotonImage): void;
declare function horizontal_strips(photon_image: PhotonImage, num_strips: number): void;
declare function hsl(photon_image: PhotonImage, mode: string, amt: number): void;
declare function hsluv(photon_image: PhotonImage, mode: string, amt: number): void;
declare function hsv(photon_image: PhotonImage, mode: string, amt: number): void;
declare function hue_rotate_hsl(img: PhotonImage, degrees: number): void;
declare function hue_rotate_hsluv(img: PhotonImage, degrees: number): void;
declare function hue_rotate_hsv(img: PhotonImage, degrees: number): void;
declare function hue_rotate_lch(img: PhotonImage, degrees: number): void;
declare function identity(photon_image: PhotonImage): void;
declare function inc_brightness(photon_image: PhotonImage, brightness: number): void;
declare function invert(photon_image: PhotonImage): void;
declare function laplace(photon_image: PhotonImage): void;
declare function lch(photon_image: PhotonImage, mode: string, amt: number): void;
declare function lighten_hsl(img: PhotonImage, level: number): void;
declare function lighten_hsluv(img: PhotonImage, level: number): void;
declare function lighten_hsv(img: PhotonImage, level: number): void;
declare function lighten_lch(img: PhotonImage, level: number): void;
declare function lix(photon_image: PhotonImage): void;
declare function lofi(img: PhotonImage): void;
declare function mix_with_colour(photon_image: PhotonImage, mix_colour: Rgb, opacity: number): void;
declare function monochrome(img: PhotonImage, r_offset: number, g_offset: number, b_offset: number): void;
declare function monochrome_tint(img: PhotonImage, rgb_color: Rgb): void;
declare function multiple_offsets(photon_image: PhotonImage, offset: number, channel_index: number, channel_index2: number): void;
declare function neue(photon_image: PhotonImage): void;
declare function noise_reduction(photon_image: PhotonImage): void;
declare function normalize(photon_image: PhotonImage): void;
declare function obsidian(img: PhotonImage): void;
declare function offset(photon_image: PhotonImage, channel_index: number, offset: number): void;
declare function offset_blue(img: PhotonImage, offset_amt: number): void;
declare function offset_green(img: PhotonImage, offset_amt: number): void;
declare function offset_red(img: PhotonImage, offset_amt: number): void;
declare function oil(photon_image: PhotonImage, radius: number, intensity: number): void;
declare function open_image(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D): PhotonImage;
declare function padding_bottom(img: PhotonImage, padding: number, padding_rgba: Rgba): PhotonImage;
declare function padding_left(img: PhotonImage, padding: number, padding_rgba: Rgba): PhotonImage;
declare function padding_right(img: PhotonImage, padding: number, padding_rgba: Rgba): PhotonImage;
declare function padding_top(img: PhotonImage, padding: number, padding_rgba: Rgba): PhotonImage;
declare function padding_uniform(img: PhotonImage, padding: number, padding_rgba: Rgba): PhotonImage;
declare function pastel_pink(img: PhotonImage): void;
declare function pink_noise(photon_image: PhotonImage): void;
declare function pixelize(photon_image: PhotonImage, pixel_size: number): void;
declare function prewitt_horizontal(photon_image: PhotonImage): void;
declare function primary(img: PhotonImage): void;
declare function putImageData(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D, new_image: PhotonImage): void;
declare function r_grayscale(photon_image: PhotonImage): void;
declare function remove_blue_channel(img: PhotonImage, min_filter: number): void;
declare function remove_channel(img: PhotonImage, channel: number, min_filter: number): void;
declare function remove_green_channel(img: PhotonImage, min_filter: number): void;
declare function remove_red_channel(img: PhotonImage, min_filter: number): void;
declare function resample(img: PhotonImage, dst_width: number, dst_height: number): PhotonImage;
declare function resize(photon_img: PhotonImage, width: number, height: number, sampling_filter: SamplingFilter): PhotonImage;
declare function resize_img_browser(photon_img: PhotonImage, width: number, height: number, sampling_filter: SamplingFilter): HTMLCanvasElement;
declare function rotate(photon_img: PhotonImage, angle: number): PhotonImage;
declare function ryo(photon_image: PhotonImage): void;
declare function saturate_hsl(img: PhotonImage, level: number): void;
declare function saturate_hsluv(img: PhotonImage, level: number): void;
declare function saturate_hsv(img: PhotonImage, level: number): void;
declare function saturate_lch(img: PhotonImage, level: number): void;
declare function seam_carve(img: PhotonImage, width: number, height: number): PhotonImage;
declare function selective_color_convert(photon_image: PhotonImage, ref_color: Rgb, new_color: Rgb, fraction: number): void;
declare function selective_desaturate(img: PhotonImage, ref_color: Rgb, amt: number): void;
declare function selective_greyscale(photon_image: PhotonImage, ref_color: Rgb): void;
declare function selective_hue_rotate(photon_image: PhotonImage, ref_color: Rgb, degrees: number): void;
declare function selective_lighten(img: PhotonImage, ref_color: Rgb, amt: number): void;
declare function selective_saturate(img: PhotonImage, ref_color: Rgb, amt: number): void;
declare function sepia(img: PhotonImage): void;
declare function sharpen(photon_image: PhotonImage): void;
declare function shearx(photon_img: PhotonImage, shear: number): PhotonImage;
declare function sheary(photon_img: PhotonImage, shear: number): PhotonImage;
declare function single_channel_grayscale(photon_image: PhotonImage, channel: number): void;
declare function sobel_global(photon_image: PhotonImage): void;
declare function sobel_horizontal(photon_image: PhotonImage): void;
declare function sobel_vertical(photon_image: PhotonImage): void;
declare function solarize(photon_image: PhotonImage): void;
declare function solarize_retimg(photon_image: PhotonImage): PhotonImage;
declare function swap_channels(img: PhotonImage, channel1: number, channel2: number): void;
declare function threshold(img: PhotonImage, threshold: number): void;
declare function tint(photon_image: PhotonImage, r_offset: number, g_offset: number, b_offset: number): void;
declare function to_image_data(photon_image: PhotonImage): ImageData;
declare function to_raw_pixels(imgdata: ImageData): Uint8Array;
declare function vertical_strips(photon_image: PhotonImage, num_strips: number): void;
declare function watermark(img: PhotonImage, watermark: PhotonImage, x: bigint, y: bigint): void;

// Class declarations

declare class PhotonImage {
  constructor(raw_pixels: Uint8Array, width: number, height: number);
  static new_from_base64(base64: string): PhotonImage;
  static new_from_byteslice(vec: Uint8Array): PhotonImage;
  static new_from_blob(blob: Blob): PhotonImage;
  static new_from_image(image: HTMLImageElement): PhotonImage;
  get_width(): number;
  get_raw_pixels(): Uint8Array;
  get_height(): number;
  get_base64(): string;
  get_bytes(): Uint8Array;
  get_bytes_jpeg(quality: number): Uint8Array;
  get_bytes_webp(): Uint8Array;
  get_image_data(): ImageData;
  set_imgdata(img_data: ImageData): void;
  get_estimated_filesize(): bigint;
  free(): void;
}

declare class Rgb {
  constructor(r: number, g: number, b: number);
  set_red(r: number): void;
  set_green(g: number): void;
  set_blue(b: number): void;
  get_red(): number;
  get_green(): number;
  get_blue(): number;
  free(): void;
}

declare class Rgba {
  constructor(r: number, g: number, b: number, a: number);
  set_red(r: number): void;
  set_green(g: number): void;
  set_blue(b: number): void;
  set_alpha(a: number): void;
  get_red(): number;
  get_green(): number;
  get_blue(): number;
  get_alpha(): number;
  free(): void;
}

// Enum declarations

declare enum SamplingFilter {
  Nearest = 1,
  Triangle = 2,
  CatmullRom = 3,
  Gaussian = 4,
  Lanczos3 = 5
}

// Helper functions
declare function copy(source: PhotonImage): PhotonImage;
declare function copy(source: PhotonImage, dest: PhotonImage): PhotonImage;
declare function createImage(width: number, height: number, color?: Rgba): PhotonImage;
declare function createImageWithSizeTemplate(template: string, color?: Rgba): PhotonImage;
declare function rgba(r: number, g: number, b: number, a: number): Rgba;
declare function paste(source: PhotonImage, target: PhotonImage, x0: number, y0: number, x1?: number, y1?: number): PhotonImage;

// User code entry point
declare function main(image: PhotonImage): PhotonImage | void;